### ISSUE TITLE
Documentation Sanitization

### ISSUE THREAD

**Issue by stevebaranski** [Electrode-iOS/ELRouter#31]
Consider replacing the objectionable language with a substantive description:
https://github.com/Electrode-iOS/ELRouter/blob/master/ELRouter/Route.swift#L195

**Comment by bsneed** [comment]
possibly helpful,

It works that way because:

- It's marked as .fixed (it used to be .static when I wrote it), thus making it a static controller.
- all other types create a new instance of the controller to be used.
- whereas .fixed needs to instantiate once, and then return the same value every time.

Additional:

Consider changing either .fixed back to .static, or change staticValue to fixedValue.
